# Generated by Django 3.0.5 on 2020-05-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkClass',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('src_ip', models.TextField(blank=True, db_column='Src IP', null=True)),
                ('src_port', models.BigIntegerField(blank=True, db_column='Src Port', null=True)),
                ('dst_ip', models.TextField(blank=True, db_column='Dst IP', null=True)),
                ('dst_port', models.BigIntegerField(blank=True, db_column='Dst Port', null=True)),
                ('timestamp', models.TextField(blank=True, db_column='Timestamp', null=True)),
                ('class_field', models.TextField(blank=True, db_column='Class', null=True)),
            ],
            options={
                'db_table': 'network_class',
                'managed': True,
            },
        ),
    ]
